version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # Note: version as string
  git:
    clone_branch_override: "master"  # String format

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:  # Correct format specification
  - htmlzip
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
