# .readthedocs.yaml
version: 2

# Explicitly set default branch
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  git:
    clone_branch: main  # ← Add this line

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .

# Output formats
formats:
  - html
  - pdf
  - epub
